# Generated by `tirith setup cline` on Windows. Do not edit; re-run setup to
# refresh it.
#
# Cline's Windows hook runtime runs this file with
#   pwsh -NoProfile -NonInteractive -ExecutionPolicy Bypass -File PreToolUse.ps1
# passing the PreToolUse event as JSON on stdin and reading the decision JSON
# from stdout. This script is the Windows counterpart of the POSIX `#!/bin/sh`
# wrapper: Cline injects no environment, so the Tirith path, the wire protocol,
# and the adapter location are baked in here, and it forwards stdin and stdout
# through the shared Python adapter unchanged.
$ErrorActionPreference = 'Stop'

$env:TIRITH_BIN = '__TIRITH_BIN__'
$env:TIRITH_HOOK_PROTOCOL = 'cline'

function Write-TirithFallback([string]$message) {
    if ($env:TIRITH_FAIL_OPEN -eq '1') {
        Write-Output '{"cancel":false}'
    } else {
        [ordered]@{ cancel = $true; errorMessage = $message } | ConvertTo-Json -Compress
    }
}

# Read the whole event before spawning, so a closed stdin cannot deadlock.
$raw = [Console]::In.ReadToEnd()

$pythonPath = '__PYTHON_BIN__'
if (-not (Test-Path -LiteralPath $pythonPath -PathType Leaf)) {
    # No interpreter to run the adapter. Cline runs the tool when a hook fails,
    # so a fail-open opt-out is honoured; otherwise cancel, matching the adapter.
    Write-TirithFallback 'tirith: configured Python interpreter is unavailable; re-run setup or set TIRITH_FAIL_OPEN=1'
    exit 0
}

try {
    $decision = ($raw | & $pythonPath '__ADAPTER_PATH__' | Out-String).Trim()
    $code = $LASTEXITCODE
} catch {
    Write-TirithFallback 'tirith: hook adapter could not be started; re-run setup or set TIRITH_FAIL_OPEN=1'
    exit 0
}

if (-not $decision) {
    Write-TirithFallback "tirith: hook adapter exited without a decision (exit code $code)"
    exit 0
}

# A malformed stdout value is equivalent to no decision: Cline otherwise
# treats a hook parse failure as permission to continue.
try {
    $parsedDecision = $decision | ConvertFrom-Json -ErrorAction Stop
    if (($null -eq $parsedDecision.cancel) -or ($parsedDecision.cancel -isnot [bool])) {
        throw 'decision is missing a boolean cancel field'
    }
} catch {
    Write-TirithFallback 'tirith: hook adapter returned an invalid decision'
    exit 0
}

Write-Output $decision
exit 0
